# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='yazar',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
